# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gr/Documents/workspace/USU/P_Prog/PVZ/PvZ

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gr/Documents/workspace/USU/P_Prog/PVZ/PvZ

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gr/Documents/workspace/USU/P_Prog/PVZ/PvZ/CMakeFiles /home/gr/Documents/workspace/USU/P_Prog/PVZ/PvZ/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gr/Documents/workspace/USU/P_Prog/PVZ/PvZ/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PvZ

# Build rule for target.
PvZ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PvZ
.PHONY : PvZ

# fast build rule for target.
PvZ/fast:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/build
.PHONY : PvZ/fast

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Board.cpp.s
.PHONY : Board.cpp.s

BoardRow.o: BoardRow.cpp.o

.PHONY : BoardRow.o

# target to build an object file
BoardRow.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/BoardRow.cpp.o
.PHONY : BoardRow.cpp.o

BoardRow.i: BoardRow.cpp.i

.PHONY : BoardRow.i

# target to preprocess a source file
BoardRow.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/BoardRow.cpp.i
.PHONY : BoardRow.cpp.i

BoardRow.s: BoardRow.cpp.s

.PHONY : BoardRow.s

# target to generate assembly for a file
BoardRow.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/BoardRow.cpp.s
.PHONY : BoardRow.cpp.s

GameModel.o: GameModel.cpp.o

.PHONY : GameModel.o

# target to build an object file
GameModel.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/GameModel.cpp.o
.PHONY : GameModel.cpp.o

GameModel.i: GameModel.cpp.i

.PHONY : GameModel.i

# target to preprocess a source file
GameModel.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/GameModel.cpp.i
.PHONY : GameModel.cpp.i

GameModel.s: GameModel.cpp.s

.PHONY : GameModel.s

# target to generate assembly for a file
GameModel.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/GameModel.cpp.s
.PHONY : GameModel.cpp.s

PeaShooter.o: PeaShooter.cpp.o

.PHONY : PeaShooter.o

# target to build an object file
PeaShooter.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/PeaShooter.cpp.o
.PHONY : PeaShooter.cpp.o

PeaShooter.i: PeaShooter.cpp.i

.PHONY : PeaShooter.i

# target to preprocess a source file
PeaShooter.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/PeaShooter.cpp.i
.PHONY : PeaShooter.cpp.i

PeaShooter.s: PeaShooter.cpp.s

.PHONY : PeaShooter.s

# target to generate assembly for a file
PeaShooter.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/PeaShooter.cpp.s
.PHONY : PeaShooter.cpp.s

Plant.o: Plant.cpp.o

.PHONY : Plant.o

# target to build an object file
Plant.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Plant.cpp.o
.PHONY : Plant.cpp.o

Plant.i: Plant.cpp.i

.PHONY : Plant.i

# target to preprocess a source file
Plant.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Plant.cpp.i
.PHONY : Plant.cpp.i

Plant.s: Plant.cpp.s

.PHONY : Plant.s

# target to generate assembly for a file
Plant.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Plant.cpp.s
.PHONY : Plant.cpp.s

PlantBullet.o: PlantBullet.cpp.o

.PHONY : PlantBullet.o

# target to build an object file
PlantBullet.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/PlantBullet.cpp.o
.PHONY : PlantBullet.cpp.o

PlantBullet.i: PlantBullet.cpp.i

.PHONY : PlantBullet.i

# target to preprocess a source file
PlantBullet.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/PlantBullet.cpp.i
.PHONY : PlantBullet.cpp.i

PlantBullet.s: PlantBullet.cpp.s

.PHONY : PlantBullet.s

# target to generate assembly for a file
PlantBullet.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/PlantBullet.cpp.s
.PHONY : PlantBullet.cpp.s

Zombie.o: Zombie.cpp.o

.PHONY : Zombie.o

# target to build an object file
Zombie.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Zombie.cpp.o
.PHONY : Zombie.cpp.o

Zombie.i: Zombie.cpp.i

.PHONY : Zombie.i

# target to preprocess a source file
Zombie.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Zombie.cpp.i
.PHONY : Zombie.cpp.i

Zombie.s: Zombie.cpp.s

.PHONY : Zombie.s

# target to generate assembly for a file
Zombie.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/Zombie.cpp.s
.PHONY : Zombie.cpp.s

ZombieController.o: ZombieController.cpp.o

.PHONY : ZombieController.o

# target to build an object file
ZombieController.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/ZombieController.cpp.o
.PHONY : ZombieController.cpp.o

ZombieController.i: ZombieController.cpp.i

.PHONY : ZombieController.i

# target to preprocess a source file
ZombieController.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/ZombieController.cpp.i
.PHONY : ZombieController.cpp.i

ZombieController.s: ZombieController.cpp.s

.PHONY : ZombieController.s

# target to generate assembly for a file
ZombieController.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/ZombieController.cpp.s
.PHONY : ZombieController.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PvZ.dir/build.make CMakeFiles/PvZ.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PvZ"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... BoardRow.o"
	@echo "... BoardRow.i"
	@echo "... BoardRow.s"
	@echo "... GameModel.o"
	@echo "... GameModel.i"
	@echo "... GameModel.s"
	@echo "... PeaShooter.o"
	@echo "... PeaShooter.i"
	@echo "... PeaShooter.s"
	@echo "... Plant.o"
	@echo "... Plant.i"
	@echo "... Plant.s"
	@echo "... PlantBullet.o"
	@echo "... PlantBullet.i"
	@echo "... PlantBullet.s"
	@echo "... Zombie.o"
	@echo "... Zombie.i"
	@echo "... Zombie.s"
	@echo "... ZombieController.o"
	@echo "... ZombieController.i"
	@echo "... ZombieController.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

